---

- name: Use a single private IPv4 address if we have no public IPv4 address
  include_vars: private_IPv4_only.yml
  when: tor_v4ips == []

# workaround for this ansible IPv6 filter bug
# https://github.com/ansible/ansible/issues/14829
# we simply convert False to empty lists
- name: workaround for ansible bug 14829 (1/3)
  set_fact:
    tor_available_public_ipv6s: []
  when: tor_available_public_ipv6s == False

- name: workaround for ansible bug 14829 (2/3)
  set_fact:
    tor_v6ips: "{{ tor_available_public_ipv6s[0:tor_ipv4_count|int]|ipv6('address') }}"

- name: workaround for ansible bug 14829 (3/3)
  set_fact:
    tor_v6ips: []
  when: tor_v6ips == False

- name: setup IP list (1/2)
  set_fact:
    ips:
        ipv4: "{{ item.0 }}"
        ipv6: "{{ item.1 }}"
  with_together:
        - "{{ tor_v4ips }}"
        - "{{ tor_v6ips }}"
  register: tor_ipsinterm

- name: setup IP list (2/2)
  set_fact:
    tor_ips: "{{ tor_ipsinterm.results | map(attribute='ansible_facts.ips')|list}}"
